#!/usr/bin/env node

(function(){
  var zmq = require('zmq');

  var service = zmq.socket('rep');
  service.on('message', function(){
    var frames = Array.apply(null, arguments);
    console.log("Service received: %s", frames);
    if(frames[0].toString()){
      frames[0] = "Hello World";
      service.send(frames);
    }
  });
  service.bind('tcp://*:6666');
})();
